-- ============================================================
-- ⚠️ このファイルは supabase_security_rls.sql に統合されました
-- ============================================================
-- 新規実行・本番適用は supabase_security_rls.sql を使用してください。
--
-- 内容:
--   - KARiN.NOTES / NEWS の RLS・GRANT・POLICY
--   - comments アーカイブ（公開遮断）
--   - 管理系テーブル一式の RLS + REVOKE
--   - blog-images Storage ポリシー
--   - article_type スキーマ
--
-- 新規実行・本番適用は supabase_security_rls.sql を使用してください。
-- （\echo は Supabase SQL Editor 非対応のためコメントのみ）
